### ISSUE TITLE
Summoning Jutsu: Snake

### ISSUE THREAD

**Issue by RTDjay** [IllusiveBIair/Naruto-Evolution-Community#17]
The summoning jutsu: Snake doesn’t do anything sadly. I summon it but it just follows the person around without doing damage. I think Blair had put this on the to do list, but I know how busy you guys are so I’ll keep this here for a more organized way of things.

**Comment by IllusiveBIair** [comment]
I appreciate it Jay, thanks it's on my list of things to look into.

**Comment by IllusiveBIair** [comment]
Fixed, coming in the next hotfix.

**Comment by RTDjay** [comment]
Thanks 🙌🏼
