### ISSUE TITLE
Flying Thunder God : Great Escape triggers whenever your HP regenerates

### ISSUE THREAD

**Issue by Haikuno** [IllusiveBIair/Naruto-Evolution-Community#19]
**Bug Report:**
Title.

**Steps to Reproduce:**
*Steps to reproduce the undesired behavior.*
1. Get damaged
2. Cast the jutsu
3. Wait for HP regeneration

**Expected Behavior:**
The jutsu should only trigger whenever you take damage.

**Comment by IllusiveBIair** [comment]
This issue is resolved and will be coming in the next hotfix. Thank you!
