### ISSUE TITLE
Activating Flying Thunder God after killing a clone with your Kunai teleports you to the void

### ISSUE THREAD

**Issue by Haikuno** [IllusiveBIair/Naruto-Evolution-Community#20]
**Bug Report:**
Title.

**Steps to Reproduce:**
*Steps to reproduce the undesired behavior.*
1. Cast Flying Thunder God : Kunai
2. Clone should die if you have enough damage. Haven't tested it when the clone doesn't die.
3. Cast Flying Thunder God

**Expected Behavior:**
You shouldn't be able to cast Flying Thunder God on non-existant targets.

**Additional Information:**
I would also test this when killing a player and trying to tp to them after them respawning, I would guess it TP's you to their hospital or something.

**Comment by IllusiveBIair** [comment]
This seems to have been fixed indirectly during my other fixes of the FTG jutsus. After the next hotfix if you could try and see if the bug still occurs I would appreciate it.

**Comment by Haikuno** [comment]
Sure thing!

**Comment by douglasparker** [comment]
@Haikuno Can you confirm if this has been fixed or not? Thank you.

**Comment by IllusiveBIair** [comment]
I'm going to close this issue since I've had no further word that the bug still occurs.
