### ISSUE TITLE
Spider summon buff

### ISSUE THREAD

**Issue by NotHybrid** [IllusiveBIair/Naruto-Evolution-Community#34]
Damage and all that is fine but 1.2k chakra usage is a lottt this shit be makin me run out of chakra before i even finish my combo.. rather just use my earth dragon do more dmg and use less chakra lol

but yeah i'd like to see a chakra usage reduction on the spider summon

**Comment by IllusiveBIair** [comment]
I looked into the jutsu and it's currently taking away 750 chakra not 1200. At this time I believe this to be a fair amount, if you're running out of chakra too much I would advise investing in more chakra.
