### ISSUE TITLE
Nara nerf that won’t affect their damage.

### ISSUE THREAD

**Issue by RTDjay** [IllusiveBIair/Naruto-Evolution-Community#39]
Nara moves happen so fast, that I feel as though instead of nerfing the damage just put a slight delay after each jutsu so people can actually advance sub it before getting hit with all 3 nara bind jutsus at the exact same time.

**Comment by NotHybrid** [comment]
FAX

**Comment by IllusiveBIair** [comment]
Alright, should be a lot more manageable now.

IllusiveBIair/Naruto-Evolution#137
