### ISSUE TITLE
Retiring as Kazekage has some bugged text

### ISSUE THREAD

**Issue by Haikuno** [IllusiveBIair/Naruto-Evolution-Community#40]
**Bug Report:**
When retiring as Kazekage (and I would guess Hokage as well), you get the following text : (Successor) has accepted your invitation to succeed you as Chuunin.

Particularly as Kazekage, it says you're retiring from Kazekage for the Hidden Leaf.

**Steps to Reproduce:**
*Steps to reproduce the undesired behavior.*
1. Retire as Kazekage
2. Choose a successor
3. See error

**Screenshots:**
![hidden leaf](https://user-images.githubusercontent.com/67402084/132107210-5c31dd44-6e95-4a48-996b-039c72da8c0c.png)

**Additional Information:**
I was Chuunin before geting Kazekage, so I would guess the text when someone succeeds you for some reason grabs your rank after retiring instead of your previous rank.

**Comment by douglasparker** [comment]
This is resolved in the next patch.
