### ISSUE TITLE
Gates needs to take less HP on opening them

### ISSUE THREAD

**Issue by CoderMan123** [IllusiveBIair/Naruto-Evolution-Community#41]
Gates users have their HP drained too much, I feel that lowering the hp drain while opening the gates up or drain while using them would make the clan better, because atm they are basically killing themselves then dying to one attack.

Another thing that can be changed is reduce the amount of time it takes to get to the 5th gate

**Comment by IllusiveBIair** [comment]
Done.

IllusiveBIair/Naruto-Evolution#137
