### ISSUE TITLE
A rank escort mission bug.

### ISSUE THREAD

**Issue by RTDjay** [IllusiveBIair/Naruto-Evolution-Community#42]
![A224A18E-FFAD-476E-BDCB-FEAC11FD826A](https://user-images.githubusercontent.com/89949904/132120712-f65d2d15-8ef0-433c-8df1-0e95a7cf811b.jpeg)

So this just happened twice to me, Tesoro, and TwoTwo. We just missed out on 124 exp each, hopefully ya can give that to us but the escort doesn’t go inside of this building and just disappears after a little while with no trace of exp.

**Comment by IllusiveBIair** [comment]
Can I ask does this happen with only Chichiatsu so far?

**Comment by RTDjay** [comment]
Yeah i believe so. It was only to that escort house that kept messing up.
