### ISSUE TITLE
Leftover Skill Points

### ISSUE THREAD

**Issue by RicaOrangeJuice** [IllusiveBIair/Naruto-Evolution-Community#50]
I think since skill points will eventually just be stacked there with no purpose then it would be cool if skill points could be used to convert in to stats even if it's just one to one something they could be used for.

**Comment by IllusiveBIair** [comment]
They may not have a use yet but plans for as prestige system that will allow you to make use of more skill points will be a thing in future. I'm closing this issue as we don't have any intentions on improving this as of yet beyond potentially adding more jutsu in future.

**Comment by RicaOrangeJuice** [comment]
Ok thx
