### ISSUE TITLE
Drain from Sharingan and Byakugan activing Crow sub

### ISSUE THREAD

**Issue by GuilhermeBelache** [IllusiveBIair/Naruto-Evolution-Community#53]
**Bug Report:**
Drain from Sharingan and Byakugan activing Crow sub

**Steps to Reproduce:**
1. Active Sharingan or Byakugan
2. Use Crow sub
3. Then see it being using auto when the first chakra drain comes out

**Comment by IllusiveBIair** [comment]
This should be fixed from a couple patches back.
