### ISSUE TITLE
Resolution screen on NE

### ISSUE THREAD

**Issue by GuilhermeBelache** [IllusiveBIair/Naruto-Evolution-Community#56]
**Feature Request:**
*Could you guys please make NE more "accessible" ( i guess its the right word) for someone like me who have a screen with this resolution:1366 x 768, since when we playing, our screen are act like this, and we cant (for example) use the new prec train system
![image](https://user-images.githubusercontent.com/48718338/132946910-e3db15fa-88dd-433d-9fa5-208c1408bd42.png)
.*

**Support this Feature Request:**
Please react to this issue with a 👍🏽 or 👎🏽 to show your support for this feature request.

Please leave a comment 💬 as your feedback is valuable 💎 and will be considered when making development decisions.

**Comment by CoderMan123** [comment]
They just gotta make the target practice thing not so wide

**Comment by IllusiveBIair** [comment]
IllusiveBIair/Naruto-Evolution#150
