### ISSUE TITLE
Info about when we complet our mission isnt showing anymore

### ISSUE THREAD

**Issue by GuilhermeBelache** [IllusiveBIair/Naruto-Evolution-Community#57]
**Bug Report:**
*Info about when we complet our mission isnt showing anymore.*

**Steps to Reproduce:**
*Steps to reproduce the undesired behavior.*
1. take your new mission
2. complete it
3. See "error" not showing anymore about how much exp you got, mount of RYO and etc..

**Comment by IllusiveBIair** [comment]
IllusiveBIair/Naruto-Evolution#150
