### ISSUE TITLE
New Precision Training should be a bit easier

### ISSUE THREAD

**Issue by RicaOrangeJuice** [IllusiveBIair/Naruto-Evolution-Community#60]
The new Precision Training is cool but the target is a bit hard to hit making the gains not that much better then just spamming the regular logs. 

I suggest that the logs move a little less frequently or just move in less farther distances. At the moment i feel theyove far too much to be a consistent training method

**Comment by CoderMan123** [comment]
It's just how long it takes for the damn kunai to travel, the log needs to be closer

**Comment by IllusiveBIair** [comment]
The log will now be a bit closer both for people with low resolution and to make it slightly easier. Exp from shuriken and kunai is also getting buffed.

**Comment by IllusiveBIair** [comment]
IllusiveBIair/Naruto-Evolution#150
