### ISSUE TITLE
Players should take priority when targeting with Tab.

### ISSUE THREAD

**Issue by vizzion420** [IllusiveBIair/Naruto-Evolution-Community#63]
When using Tab to target, any players should take priority over objects (Ex. being training logs). Not only this but enemy villagers (mostly meaning anyone from a different village than you) should take top priority (excluding clones of course, since those are a way to distract targeting) when tab targeting.

Pretty much players/players from different village should take priority when tab targeting compared to static objects; excluding clones.

**Comment by kauedavila** [comment]
Up to this

**Comment by GuilhermeBelache** [comment]
Up

**Comment by IllusiveBIair** [comment]
I can agree with the target dummies and similar objects however there are a number of reasons why it won't work out for villagers. Firstly there are sparring matches i.e. in the dojo and arena to consider. And second, there are targeted jutsu that one might want to use on an ally. This would lead to a significant nerf for those kinds of Jutsu. It's also a handicap mechanic for when someone is outnumbered for them to be able to hide behind other people to avoid being easily targeted by everyone at once. Training objects will however no longer be tab targetable (you can still click them to target them if you choose to).

**Comment by IllusiveBIair** [comment]
IllusiveBIair/Naruto-Evolution#150
