### ISSUE TITLE
Water sharks will hit yourself every so often

### ISSUE THREAD

**Issue by vizzion420** [IllusiveBIair/Naruto-Evolution-Community#64]
Every so often, at depending on the angle you are throwing sharks you will hit yourself. (might still hit the enemy but you will also get hit and take the damage)

**Comment by vizzion420** [comment]
Found out it is mostly always when you shoot them from a vertical up/down position.

**Comment by IllusiveBIair** [comment]
IllusiveBIair/Naruto-Evolution#150
