### ISSUE TITLE
Akimichi's Human Boulder does not allow you to control it after a target has been hit

### ISSUE THREAD

**Issue by Tesoro2** [IllusiveBIair/Naruto-Evolution-Community#7]
**Bug Report:**
*Please be as descriptive as possible.*

**Steps to Reproduce:**
*Steps to reproduce the undesired behavior.*

**Expected Behavior:**
*Please explain what the desired behavior is.*

**BYOND Server Version:**
*e.g. 513.1542*

**BYOND Client Version:**
*e.g. 513.1542*

**Error Logs / Error Messages:**
```dm
[Copy and paste error messages or drag and drop error logs here.]
```

**Screenshots:**
*Copy and paste or drag and drop images here to upload screenshots.*

**Additional Information:**
*Please provide any additional information that may be of help to us in order reproduce this bug.*

**Comment by IllusiveBIair** [comment]
I'm not seeing this issue occurring during local testing, it is intentional for you to not be able to do a 180 turn while in human boulder you should only be able to turn left or right (relative to the direction you are moving in). Can you reconfirm that this is an issue for me?

**Comment by IllusiveBIair** [comment]
Alright closing this issue as it's been resolved.
