### ISSUE TITLE
Cooldowns on top right

### ISSUE THREAD

**Issue by CoderMan123** [IllusiveBIair/Naruto-Evolution-Community#71]
![CDucked](https://user-images.githubusercontent.com/88360246/133374883-984c6cf8-0a9a-4e95-94c6-908e94a99217.png)

The cooldowns at the top right overlap eachother when using alot of jutsus, also on a Tai build some of the tai moves bump the cooldowns lower and lower until they go completely off screen.

**Comment by douglasparker** [comment]
Resolved in IllusiveBIair/Naruto-Evolution@5fcd95b53788e99465c23218518a7b8729f0c450
