### ISSUE TITLE
Automatic Hokage Bug

### ISSUE THREAD

**Issue by CoderMan123** [IllusiveBIair/Naruto-Evolution-Community#73]
### Bug Report

I'm Hokage but can't S rank, my rank still says Chunin although, it says I'm declared as Hokage and have access to all perms 

### Expected Behavior

Become Hokage and have accesss to all mish's 

### Steps to Reproduce

Become hokage from ballouts

**Comment by douglasparker** [comment]
This is resolved in the next update. In the meantime, I will login and fix your rank.
