### ISSUE TITLE
Morning Peacock and Leaf Whirlwind are unable to be used again after the cooldown expires

### ISSUE THREAD

**Issue by CoderMan123** [IllusiveBIair/Naruto-Evolution-Community#74]
### Bug Report

Update: Figured it out, So morning peacock can only be used once, when trying to use it the 2nd time it will never go off again
Update2: This also happens with leaf whirlwind
### Steps to Reproduce

Use morning peacock once, then try to use it again, it won't go off

**Comment by douglasparker** [comment]
This is resolved in the next patch.
