### ISSUE TITLE
Kazekage and HP bugs

### ISSUE THREAD

**Issue by RTDjay** [IllusiveBIair/Naruto-Evolution-Community#76]
### Bug Report

So first is the Kazekage bug, it still identifies the Kazekage as the hokage and gives them hokage clothing. And next is you can’t retire as the Kazekage or else the successor will become the “Hokage” aswell and you will keep the role making multiple kages at a time. This causes the person that retired to have no HP bar, or hot keys on there screen and still have the leader tab. 

### Expected Behavior

Kage sadness

### Steps to Reproduce

I think there is something in the code switching about Kazekage and hokage and messing it up. 

### BYOND Client Version

Newest one

### Form Completion and Accuracy

- [X] I confirm that this form has been completed in full and is accurate to the best of my knowledge.

**Comment by douglasparker** [comment]
Resolved in commit https://github.com/IllusiveBIair/Naruto-Evolution/commit/ea6d9fb3a261fb0de83417fee3d6855ab871e45a

**Comment by douglasparker** [comment]
I believe this was fixed in release: [2.4.6](https://github.com/IllusiveBIair/Naruto-Evolution-Community/releases/tag/2.4.6).

Can you please confirm that the issue with your health bar is resolved? You may need to be promoted to Kazekage once more, but the UI issues should be resolved immediately.
