### ISSUE TITLE
Character Deletion

### ISSUE THREAD

**Issue by Juxnist** [IllusiveBIair/Naruto-Evolution-Community#78]
### Bug Report

Deleting a character will not free up the character name to be used again.

### Expected Behavior

I'd expect to be able to reuse my desired name.

### Steps to Reproduce

1. Create character
2.  Delete character
3.  Create another character with the same name used for the first one.

### BYOND Server Version

514.1566

### BYOND Client Version

514.1566

### Form Completion and Accuracy

- [X] I confirm that this form has been completed in full and is accurate to the best of my knowledge.

**Comment by douglasparker** [comment]
This was resolved in version: 2.4.13
https://github.com/IllusiveBIair/Naruto-Evolution/commit/c67a47052da4b030c1fa381d49f40490a6d3775e
