### ISSUE TITLE
Killing wild animals gives you a bounty and also notifies everyone about it.

### ISSUE THREAD

**Issue by Haikuno** [IllusiveBIair/Naruto-Evolution-Community#8]
**Bug Report:**
The title should be self-explanatory enough.

**Steps to Reproduce:**
1. Kill any wild animal

**Expected Behavior:**
I think you shouldn't get bounty nor should be anyone notified by it.

**BYOND Client Version:**
514.1566

**Comment by IllusiveBIair** [comment]
Thank you, I'm looking into this now.

**Comment by IllusiveBIair** [comment]
IllusiveBIair/Naruto-Evolution@72056205a1f33fdb4b9851d48a321a0588f14258
